### ISSUE TITLE
problem with Gnome 43

### ISSUE THREAD

**Issue by mhkarimi1383** [realmazharhussain/gdm-settings#100]
### What happened?

After hitting apply and restart my desktop (GDM and GNOME Desktop) control panel screwed up
and there is no style there  

### Expected behavior

just a simple change in GDM

### To Reproduce

try it on GNOME 43

### Application Version

Latest from AUR (non git version)

### Source

AUR

### Environment

- **OS**:  ArchLinux
- **GNOME**:  43.beta

**Comment by realmazharhussain** [comment]
By control panel, do you mean `gnome-control-center` i.e. the settings app?

Can I get a screenshot, please?

**Comment by mhkarimi1383** [comment]
![Screenshot from 2022-09-04 23-59-50](https://user-images.githubusercontent.com/28821440/188330478-3992d551-09a9-4bdf-8a53-4749eb2da1c6.png)

**Comment by realmazharhussain** [comment]
Did you change shell theme in the app? If yes then that is what is causing this issue.

Since GNOME 43 is not released yet, almost all of the available shell themes will be incomplete i.e. not compatible with GNOME Shell 43.

I could change how shell themes are applied but that change will have to happen in v1.1 or v2.0 of the app since v1.0 is in beta and such significant changes should not be applied to it.

**Comment by realmazharhussain** [comment]
I have fixed the issue. Install `gdm-settings-git` package from the AUR (or update if already installed) and see if it works for you.
