### ISSUE TITLE
Applying configuration breaks top Gnome shell top bar position (Gnome 43)

### ISSUE THREAD

**Issue by bramvanoploo** [realmazharhussain/gdm-settings#117]
### What happened?

After selecting a gdm wallpaper image and a gnome shell theme from the gdm-settings app and applying these settings I rebooted the OS. This resulted in the top bar being out of position after login in again. I haven't been able to fix this or to exactly pinpoint what went wrong.

![image](https://user-images.githubusercontent.com/278582/193246352-f082aa5e-dd42-4b73-a946-141a2a70c1c1.png)

### Expected behavior

Applying the configuration should not affect the desktop.

### To Reproduce

Apply gdm configuration on Fedora 37 (gnome 43)

### Application Version

1.0

### Source

Flatpak

### Environment

- **OS**: Fedora 37
- **GNOME**: 43

**Comment by realmazharhussain** [comment]
It seems like your shell theme is broken.

The only way to change shell theme for GDM is to change it for the whole system including user session. But that is not a problem since the shell theme can be changed per-user with GNOME Tweaks app.

But if the shell theme you choose for both GDM and user session is broken, there is nothing this app or the extension can do for you.

If you would like to see for sure if this is a problem with the chosen shell theme, you could change your shell theme for the user session to 'default-pure' and see if the problem goes away. If it does, it means the problem is in the chosen shell theme.

**Comment by bramvanoploo** [comment]
I've tried every theme available including the default, but that didn't fix it. Maybe something coincidentally broke when saving the settings then...

**Comment by realmazharhussain** [comment]
Even changing both the GDM and user session shell themes to default?

**Comment by bramvanoploo** [comment]
That was the first thing I tried after it broke.

**Comment by realmazharhussain** [comment]
First,

1. Open Tweaks app.
2. Go to Appearance tab.
3. Change shell theme to '_Default_'.

Then,

1. Reinstall `gnome-shell` package (or `gnome-shell-common` package if it exists in your distro).
4. Unzip and install [this flatpak](https://github.com/realmazharhussain/gdm-settings/files/9691886/gdm-settings.flatpak.zip).
5. Run the app using the command `flatpak run io.github.realmazharhussain.GdmSettings//master`.
6. Go to Appearance tab.
7. Change shell theme to 'default'.
8. Apply.
9. Log out and log in (or restart).

Tell me if it fixes the problem.
