### ISSUE TITLE
gdm-settings seems half translated

### ISSUE THREAD

**Issue by libreajans** [realmazharhussain/gdm-settings#122]
### What happened?

Hi, I build gdm-settings to test translation from source but it seems half translated. .blp related files seems untranslated but translations are there.

![Ekran Görüntüsü - 2022-10-08 23-12-31](https://user-images.githubusercontent.com/6218679/194726286-1afa158a-b4ec-4fb6-a044-367a7c36842f.png)
[tr.zip](https://github.com/realmazharhussain/gdm-settings/files/9740204/tr.zip)

### Expected behavior

This strings should be translade.

### To Reproduce

Compile against the recent version with translations and test it on a translated language.

### Application Version

2.alpha

### Source

Source Code build using flatpak

### Environment

- **OS**: Ubuntu 22.04.1
- **GNOME**:  42.4

**Comment by realmazharhussain** [comment]
This problem also occurs on the AppImage. It seems like there is no way to tell the C libraries like GTK4 (which is responsible for translating strings found in `.blp` files) about non-standard locale directories (directories which actually contain the translations) from inside Python code.

This issue can be seen on other Python/GTK apps too (like GNOME Tweaks) when you install them on non-standard locations e.g. `/usr/local` instead of `/usr`.

I tried a lot of different ways to mitigate this issue but I've had no luck.

**Comment by libreajans** [comment]
I also can help you to check translation error before release. Just send me a mail (https://github.com/realmazharhussain/gdm-settings/blob/main/po/tr.po#L11) or tag me in a issue. Thank for GDM Settins app.

**Comment by realmazharhussain** [comment]
I do not understand. By "to check translation", do you mean 'proofreading' it?

**Comment by libreajans** [comment]
To test translations work properly.

Mazhar Hussain ***@***.***>, 12 Eki 2022 Çar, 10:35 tarihinde
şunu yazdı:
