### ISSUE TITLE
[BUG] Disappear user list after changing bacground on Ubuntu 22.04

### ISSUE THREAD

**Issue by 4815162342lost** [realmazharhussain/gdm-settings#38]
### What happened?

Hello, i installed gdm-settings on Ubuntu 22.04 with "Method 2".

After that i changed background:
https://i.imgur.com/rhf0ONw.png

I set this picture (/usr/share/backgrounds/warty-final-ubuntu.png) as background.

But after reboot received bug:
https://i.imgur.com/Un6P3aL.jpg

No user list visible, black line in button. I can login via "press enter -> enter password", but i do not see anything...

Screen resolution 1920x1080

### Expected behavior

Able change background on Ubuntu 22.04

### To Reproduce

Try change

### Application Version

gdm-settings v0.5.2

### Source

Source Code

### Environment

- **OS**:  Ubuntu 22.04
- **GNOME**:  gnome-shell  42.0-2ubuntu1

**Comment by 4815162342lost** [comment]
FYI, this bash-script works fine:
https://github.com/PRATAP-KUMAR/ubuntu-gdm-set-background

Maybe some Ubuntu specific bug...

**Comment by realmazharhussain** [comment]
I just added support for Ubuntu. Update to the latest version and check if that fixes your problem.
Don't forget to report back.

**Comment by realmazharhussain** [comment]
I introduced some further changes and it should work fine now.

**Comment by realmazharhussain** [comment]
@4815162342lost 

I am VERY VERY SORRY! I didn't understand your issue for so long. I feel so dumb.

Now that I looked at the pictures you uploaded with a little bit of attention, I see the problem is not with the application (except that maybe wording could be a bit better). What you are trying to change is the very small distribution logo that appears at the bottom of the login screen (for example, the Ubuntu logo). This is how GDM works and this app can't do anything about it but for some reason that little logo sits on top of everything except the top bar. So when you set a very large image as the logo, it takes over the whole screen and hides everything behind itself.

## Solution
1. Disable the logo or change it to a small picture like a 50x250 image.

   The logo setting is located in "Miscellaneous" section.
2. Set GDM background.

   The actual GDM background setting is located in the "Appearance" section.
