### ISSUE TITLE
GDM Login screen is not altered properly[BUG] 

### ISSUE THREAD

**Issue by vikashraghavan** [realmazharhussain/gdm-settings#42]
### What happened?

On changing the settings in gdm-settings (to be precise background color) brings a scroll bar next to user list and applies shadow effect. Even on resetting the themes, those effects can't be reverted.

### Expected behavior

Expected to change only the background color,

### To Reproduce

1. Open gdm-settings
2. Change background color

### Application Version

0.5.2-1	

### Source

AUR

### Environment

- **OS**:  Arch
- **GNOME**: 42.1

**Comment by realmazharhussain** [comment]
This application cannot read the settings of GDM. So, on first launch, instead of providing its own default settings, it reads user settings. When you click apply for the first time, it is basically applying all your current gnome settings to GDM (except for the settings that you changed explicitly).

Scrollbar and Shadow effect are not caused by change of GDM Background or Theme. They appear when Font Scaling has some certain values.

**To fix the problem**, open the app, go to `Fonts` page, set `Scaling Factor` to `1.00` and apply the settings.
