### ISSUE TITLE
Applying Miscellaneous -> Welcome message is not working

### ISSUE THREAD

**Issue by mahdiaqallal** [realmazharhussain/gdm-settings#47]
### What happened?

Using Fedora Silverblue 34 (Gnome 40)

In the gdm-settings settings panel for Miscellaneous -> Activate Welcome message -> Write customized Welcome message : When I change the Welcome message and click Apply, nothing is changed in Gnome Display Manager (when I lock the session and go back to it).
And when I come back to the gdm-settings settings panel, my customized Welcome message is gone, the option to display a message is deactivated 

### Expected behavior

Changing in the gdm-settings settings panel the Welcome message and clicking Apply, the customized Welcome message shoud be remembered and the option to display a message should  remain activated .

### To Reproduce

1. In the gdm-settings settings panel for Miscellaneous -> Activate Welcome message -> Write customized Welcome message
2. Click Apply and lock/unlock the Gnome session and go back to it
3. Back to the gdm-settings settings panel, my customized Welcome message is gone, the option to display a message is deactivated 

### Application Version

Version: 0.5.2         Ref: app/io.github.realmazharhussain.GdmSettings/x86_64/stable         Arch: x86_64       Branch: stable

### Source

Flatpak

### Environment

- **OS**:  Fedora Silverblue 34
- **GNOME**:  40

**Comment by realmazharhussain** [comment]
GNOME Lock Screen is not the same as GNOME Display/Login Manager. They are two different programs. If the application was working correctly, you wouldn't see the welcome message when unlocking but only when logging in.

Since the application does not seem to remember your preference, I would like you to launch the application from inside the terminal and post here any output it gives so that I can fix any errors that occur. You can launch the application from a terminal by running the command `flatpak run io.github.realmazharhussain.GdmSettings`.

**Comment by realmazharhussain** [comment]
Closing the issue since the OP @mahdiaqallal has not responded for more than 15 days. If the OP is ever ready to response, he is free to re-open the issue.
