### ISSUE TITLE
Flatpak

### ISSUE THREAD

**Issue by Doomsdayrs** [realmazharhussain/gdm-settings#8]
Consider supporting flatpak?

**Comment by realmazharhussain** [comment]
I did. But it is hard. This app requires root permissions with `pkexec` command to work. Flatpak doesn't provide that by default. I will look into this in future.

In the meantime, if anyone else can help with this issue, I will be very grateful.

**Comment by Doomsdayrs** [comment]
Are there any alternatives to using pkexec?

**Comment by realmazharhussain** [comment]
Not that I know of

**Comment by Doomsdayrs** [comment]
What are you using pkexec for specifically?

**Comment by realmazharhussain** [comment]
root access of course

**Comment by realmazharhussain** [comment]
> What are you using pkexec for specifically?

I'm using `pkexec` to run a shell script as root

**Comment by laurinneff** [comment]
You can use the `--talk-name=org.freedesktop.Flatpak` permission and `flatpak-spawn --host <any command>` or the `org.freedesktop.Flatpak.Development` D-Bus interface (documented [here](https://docs.flatpak.org/en/latest/libflatpak-api-reference.html#gdbus-org.freedesktop.Flatpak.Development)) to run a command on the host

**Comment by realmazharhussain** [comment]
Well, that can do the job but I'll have to change a lot of code. The shell script I need to run as root copies/moves some files created/modified by this app. Since `flatpak-spawn --host` runs commands on the host system, gdm-settings would have to save temporary files on the host system for the external command to have access to them. Adding `--filesystem=host` permission does not seem to give access to host's `/tmp`. In addition, I'll have to change a lot of file paths from simple `/etc`, `/usr/share`, etc. to `/run/host/etc`, `/run/host/usr/share`, etc. depending on if the app is running as a flatpak or not.

It seems like a lot of work. I may do it in future but I don't think it is going to happen soon.

**Comment by Doomsdayrs** [comment]
> Since `flatpak-spawn --host` runs commands on the host system, gdm-settings would have to save temporary files on the host system for the external command to have access to them.


For writing to host files, use XDG_DATA_DIR

**Comment by laurinneff** [comment]
It's actually `$XDG_DATA_HOME`. And for this, `$XDG_CACHE_HOME` would be even better, since they're temporary files

**Comment by realmazharhussain** [comment]
Initial Flatpak support has been added. Now, I just need to submit the application to flathub.
[gdm-settings.flatpak.zip](https://github.com/realmazharhussain/gdm-settings/files/8486272/gdm-settings.flatpak.zip)

**Comment by edwardally** [comment]
I can't boot up after apply the background color. I think is my bad that I'm using Fedora and it's not supported? anyone can help to revert back the setting?

**Comment by realmazharhussain** [comment]
@edwardally Run the command `sudo mv /usr/share/gnome-shell/gnome-shell-theme.gresource{.default,}` if you can get to a command-line interface.

**Comment by realmazharhussain** [comment]
> I think is my bad that I'm using Fedora and it's not supported?

It IS supported (as in, if you face any issue on it, I'll be happy to fix it).

@edwardally, would you mind opening an issue for your problem?

**Comment by realmazharhussain** [comment]
Since the [Flatpak](https://flathub.org/apps/details/io.github.realmazharhussain.GdmSettings) has been released on [FlatHub](https://flathub.org) for a while a now, I am closing this issue.
